import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tech In Teens</title>
        <meta name="description" content="Generated by create next app" />
        <meta name = "keywords" content = "tech , teens , programming , coding , techinteens" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.homebar}>
        <ul>
          <Link href="/"><a><li>Home</li></a></Link>
          <Link href="/links/about"><a><li>About</li></a></Link>
          <Link href="/links/learn/learn"><a><li>Learn</li></a></Link>
          <Link href="/"><a><li>Opportunities</li></a></Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Tech In Teens
        </h1>

        <p className={styles.description}>
          A place for Teenagers to share their knowledge and experience.
        </p>

        <p>
          Join TechInTeens Discord here - <a href=""></a>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
